# Generated by Django 5.0.1 on 2024-01-10 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopModel',
            fields=[
                ('id', models.UUIDField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=300)),
                ('lattitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('address', models.CharField(max_length=800)),
                ('menu', models.CharField(max_length=800)),
            ],
        ),
        migrations.CreateModel(
            name='CoupounModel',
            fields=[
                ('id', models.UUIDField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=300)),
                ('discount', models.FloatField()),
                ('shopID', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='eat_to_aid.shopmodel')),
            ],
        ),
    ]
