# Generated by Django 5.0.1 on 2024-01-10 19:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eat_to_aid', '0002_alter_coupounmodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopmodel',
            name='id',
            field=models.UUIDField(auto_created=True, default=uuid.uuid5, primary_key=True, serialize=False, unique=True),
        ),
    ]
