# Generated by Django 5.0.1 on 2024-01-11 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eat_to_aid', '0007_alter_coupounmodel_id_alter_shopmodel_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CoupounModel',
        ),
        migrations.DeleteModel(
            name='ShopModel',
        ),
    ]
