# Generated by Django 5.0.1 on 2024-01-11 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eat_to_aid', '0010_alter_coupounmodel_id_alter_shopmodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupounmodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='shopmodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
