# Generated by Django 5.0.1 on 2024-01-11 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eat_to_aid', '0011_alter_coupounmodel_id_alter_shopmodel_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupounmodel',
            old_name='shopID',
            new_name='shop',
        ),
    ]
